# Generated by Django 2.2 on 2019-04-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
